// Generated by CoffeeScript 1.9.2
var mod;

mod = require((process.cwd()) + "/src/utils");

describe('Utils', function() {
  it('should exist', function() {
    return mod.should.be.ok;
  });
  return describe('#utils', function() {
    return it('should return the right value', function() {
      return mod.utils().should.eql('Utils');
    });
  });
});
