Slack = require('slack-client')
token = 'xoxb-5042459146-mKyVHVNRYWRl80BxTb3Kqftb'
slack = new Slack(token, true, true)

makeMention = (userId) ->
  '<@' + userId + '>'

isDirect = (userId, messageText) ->
  userTag = makeMention(userId)
  messageText and messageText.length >= userTag.length and messageText.substr(0, userTag.length) == userTag



# ---
# generated by js2coffee 2.0.4

slack.on 'open', ->
  channels = Object.keys(slack.channels).map((k) ->
    slack.channels[k]
  ).filter((c) ->
    c.is_member
  ).map((c) ->
    c.name
  )
  groups = Object.keys(slack.groups).map((k) ->
    slack.groups[k]
  ).filter((g) ->
    g.is_open and !g.is_archived
  ).map((g) ->
    g.name
  )
  console.log 'Welcome to Slack. You are ' + slack.self.name + ' of ' + slack.team.name
  if channels.length > 0
    console.log 'You are in: ' + channels.join(', ')
  else
    console.log 'You are not in any channels.'
  if groups.length > 0
    console.log 'As well as: ' + groups.join(', ')
  return

slack.on 'message', (message) ->
  channel = slack.getChannelGroupOrDMByID(message.channel)
  user = slack.getUserByID(message.user)
  if message.type == 'message' and isDirect(slack.self.id, message.text)
    trimmedMessage = message.text.substr(makeMention(slack.self.id).length).trim()
    channel.send user.real_name + ' just said: ' + trimmedMessage
  return


slack.login()